### ISSUE TITLE
Wrong line-height size

### ISSUE THREAD

**Issue by stunpix** [itsthatguy/gridwax#14]
When line-height is set to some "value", horizontal lines actually rendered at "value - 1". For example if I set height to 16, space between lines is 14 pixels and line is rendered at 15th. If I set 18, space between lines is 16 pixels and line rendered at 17th pixel and so on. This leads to wrong calculations of css properties.

I'm using Chrome 34.0.1847 with OSX.

![shot1](https://cloud.githubusercontent.com/assets/129271/2850804/d0f733ee-d109-11e3-89b1-fc49fa4268cc.png)
![shot2](https://cloud.githubusercontent.com/assets/129271/2850805/d0f8008a-d109-11e3-8e33-914ecdb54bc2.png)

**Comment by radum** [comment]
This is because the border-box is not used. So for example if you say 20px line height, the div's used to display the grid will have 19px height and 1px border bottom. But is you have `box-sizing: border-box;` set to all elements this will be 19px height regardless of the border.

The script is outdated, but you can easily create a version that fits your needs.

**Comment by itsthatguy** [comment]
If you implement a fix, I'd love a pull request to merge in!

**Comment by radum** [comment]
@itsthatguy Cool, will do, I've was thinking to fork it, but this is better.
